## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
    - os: linux
      julia: 0.6
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: nightly
      env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: 0.6
      env: TESTCMD="julia"
    - os: osx
      julia: nightly
      env: TESTCMD="julia"
allow_failures:
  - julia: nightly
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
notifications:
  email: false
git:
  depth: 99999999
addons:
  apt:
    sources:
      - trusty-media
    packages:
      - ffmpeg

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg; fi

script:
 - $TESTCMD -e 'Pkg.clone(pwd()); Pkg.build("RigidBodySim"); Pkg.test("RigidBodySim"; coverage=true)'

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("RigidBodySim")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documentation
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("RigidBodySim")); include(joinpath("docs", "make.jl"))'
